Repository googleapis/python-network-connectivity, pull requests merged in 2021-04, with the labels that each got.

#20 chore: start tracking obsolete files
  synth.metadata
Labels: api: networkconnectivity, cla: yes, context: full

#21 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#22 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: networkconnectivity, cla: yes, context: full, samples

#24 chore: prevent normalization of semver versioning
  setup.py
Labels: api: networkconnectivity, cla: yes

#23 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#26 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: api: networkconnectivity, automerge, cla: yes

#25 chore(revert): revert preventing normalization
  setup.py
Labels: api: networkconnectivity, automerge, cla: yes
